name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Test work flow!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  manual_approval:
      runs-on: ubuntu-latest
      needs: build
      environment: production
      steps:
        - uses: actions/checkout@v3

        - name: Request Manual Approval
          uses: trstringer/manual-approval@v1
          with:
            secret: ${{ secrets.ACCESS_TOKEN }}
            approvers: Danushka50
            minimum-approvals: 1
            issue-title: "Deploying v1.3.5 to prod from staging"
            issue-body: "Please approve or deny the deployment of version v1.3.5."
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: ''
            additional-denied-words: ''
